language: scala
dist: trusty

scala:
  - 2.12.4

jdk:
  - oraclejdk8

script:
  - curl -L -o mill https://github.com/lihaoyi/mill/releases/download/0.2.0/0.2.0
  - chmod +x mill
  - ./mill dgraph.jar

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete